### PR TITLE
Allow handling of touch events, fix #102

### LINKED ISSUE #102: Selection not working correctly on touch device
Version: 3.1.1
Video recorded on iOS Simulator (so these clicks are actually Touch events)
bug 1

I believe this may have been introduced in this PR: https://github.com/webscopeio/react-textarea-autocomplete/pull/90 

It may be alleviated by adding onTouchStart as the same as the OnClick handler.

EDIT: Downgrading to v2.3.5 fixes this issue, so something after that must have introduced it.

### PR DESCRIPTION
**Pull request by rrikesh**
Attempt to fix #102 , tested on iOS only.

### CODE REVIEW

**Comment by jukben** [comment]
Thanks for it! If you have some time I'd be nice if you can fix also Flow issues, otherwise, I will do it during the weekend. I'm for it to merge it, better this than nothing 👍

**Comment by rrikesh** [comment]
I can't promise you on that, but I'll surely try the changes on an Android during the weekend!

**Comment by jukben** [comment]
Ok, if you can try the code on Android, it would be great, I'll take the flow issues :)

**Comment by rrikesh** [comment]
Flow errors fixed and I confirm it works on Android! You can review and merge now!

**Pull request merged**
