### PR TITLE
Fix TextArea DOM ref when specifying textAreaComponent

### PR DESCRIPTION
**Pull request by kinke**
I tried using the [react-textarea-autosize](https://github.com/andreypopp/react-textarea-autosize) component via

```js
import Textarea from 'react-textarea-autosize';
...
<ReactTextareaAutocomplete textAreaComponent={{ component: Textarea, ref: 'inputRef' }} />
```

and it failed, as the callback is firstly invoked correctly for its `inputRef`, but later also for its `ref`, so that `textareaRef` points to the `Textarea` element instead of the DOM textarea.
Also make sure the `innerRef` prop is invoked with the DOM textarea, and don't use a fresh lambda for each render (which causes the previous lambda to be invoked with nil before invoking the new one with the DOM element).

### CODE REVIEW

**Comment by jukben** [comment]
Thank you for this! I was checking this part of codebase via https://github.com/webscopeio/react-textarea-autocomplete/issues/129 and I have seen this particular issue as well. I just haven't got time to revisit it - still on my TODO. The default API version with `textAreaComponent` was working though so I gave it a lower priority. 

You rock! 💪

**Comment by jukben** [comment]
(bot)

Hey! Thank you so much for your PR! I can see that everything is green 👏.

[Here is the playground for this revision](https://837-94480675-gh.circle-artifacts.com/0/example/index.html) 🚀

I hope everything is fine! ❤️

**Comment by kinke** [comment]
Thx - I hacked around the flow issues; fixing those properly would mean a lot more work. ;)

**Comment by jukben** [comment]
Agree. The Flow is super old in this project. This gonna be a lot of work to make it shiny.

**Comment by jukben** [comment]
Released as 4.2.4 🚀 Thanks!

**Comment by kinke** [comment]
Oh wow, thanks a lot! :+1:

**Comment by oklas** [comment]
Hi @kinke, Your first post snippet has `ref: 'inputRef'`. Do you suppose `ref: 'innerRef'` instead? If so, could you create fix edition

**Comment by kinke** [comment]
Nope, `inputRef` is intended and specific to [react-textarea-autosize](https://github.com/andreypopp/react-textarea-autosize#special-props).

**Comment by oklas** [comment]
An confusion appears with these textareas. Also [react-autosize-textarea](https://github.com/buildo/react-autosize-textarea) exists but `innerRef` is intended to it. And with these packages names and usages mostly no noticeable differences. This confisions leads to hardly detectable problems although there is nothing special to fix.

**Pull request merged**
