### PR TITLE
This fix edge bug when you move to the other token by arrows

### PR DESCRIPTION
**Pull request by jukben**
Attempt to fix the bug, again :)

reference to PR #121 #120

I've apparently fixed in previous #121 another bug :)

### CODE REVIEW

**Comment by jukben** [comment]
(bot)

Hey! Thank you so much for your PR! I can see that everything is green 👏.

[Here is the playground for this revision](https://720-94480675-gh.circle-artifacts.com/0/example/index.html) 🚀

I hope everything is fine! ❤️

**Comment by jukben** [comment]
@O4epegb could you please verify that now is everything OK? 🙏

**Comment by O4epegb** [comment]
Seems good, thank you!

**Comment by jukben** [comment]
Deployed as 4.2.2 🚀

**Pull request merged**
