### PR TITLE
flow-types to type.js file

### PR DESCRIPTION
**Pull request by davidsonsns**
Issue #26 
I think it's ready. waiting feedback. :smile:

### CODE REVIEW

**Comment by davidsonsns** [comment]
@jukben could help me with these errors?

**Comment by jukben** [comment]
@davidsonsns are you sure that you made you PR from top of the master? https://github.com/webscopeio/react-textarea-autocomplete/blob/master/src/Textarea.jsx#L55

**Comment by davidsonsns** [comment]
I tuned, I forgot to run "yarn test -- -u"

**Comment by jukben** [comment]
@davidsonsns do we need to set the `style` and others to null? I don't think so if it possible we should stay with the previous implementation. Could you please check it?

**Comment by davidsonsns** [comment]
I get problems with lint if I do not set defaultProps for these props. By not being requireds.
I'm watching the [null props considered differently in getDefaultProps vs. isRequired #2166](https://github.com/facebook/react/issues/2166).
What do you think about that?

**Comment by jukben** [comment]
@davidsonsns And when you strip the props also from PropTypes? Are you still getting errors?

**Comment by davidsonsns** [comment]
yes, linst returns me errors like: `is missing in props validation`

**Comment by jukben** [comment]
I see. I've tried to myself and you are right. It's strange the errors occurs only when you use imported `types` if you define the type in the file itself is OK. 

Could you please use undefined instead of null? I think is more appropriate. Otherwise, it looks fine. Just add yourself to the contributors. :)

**Comment by davidsonsns** [comment]
I agree with undefined. update performed :top:

**Comment by jukben** [comment]
Thanks for your contribution! <3

**Pull request merged**
