### PR TITLE
fix(autocomplete): let's close the autocomple once selection is made

### LINKED ISSUE #117: Autocomplete is not triggered sometimes
Autocomplete is not triggered sometimes. I could not understand why yet, but you can reproduce it here https://codesandbox.io/s/30mrxq107m

Steps:
1) Type ":" to trigger autocompete, then close it by "Esc" key press and press "Backspace" or "Delete" to remove text
2) Type some text, like "asd", then press "Shift+Enter" to make new line, repeat it 3 times
3) Then press "Up" key to move one line upward
4) Type ":" again, nothing will happen

Strange thing, don't know why it is happening yet

### LINKED ISSUE #120: It will correctly show popup, but after you select value it will show it again for first trigger
Working great, thank you! Switched from v2 to v4 in production today.

Found only one minor bug, not sure if it is worth to fix, but here it is:

1) Type anything -> "something"
2) Trigger autocomplete -> "something @"
3) Then move caret back with arrows and trigger again -> "some@thing @"
4) Select autocomplete value
5) It will correctly show popup, but after you select value it will show it again for first trigger

Very rare edge case I suppose, but if it is not hard to fix would be cool)

_Originally posted by @O4epegb in https://github.com/webscopeio/react-textarea-autocomplete/issues/117#issuecomment-453954607_

### PR DESCRIPTION
**Pull request by jukben**
close #120

### CODE REVIEW

**Comment by jukben** [comment]
(bot)

Hey! Thank you so much for your PR! I can see that everything is green 👏.

[Here is the playground for this revision](https://701-94480675-gh.circle-artifacts.com/0/example/index.html) 🚀

I hope everything is fine! ❤️

**Comment by jukben** [comment]
Hey @O4epegb It looks I've been able to overcome it 💃

**Comment by O4epegb** [comment]
Hm, I actually just checked and it seems that the bug is still there!

**Comment by O4epegb** [comment]
Maybe we should prevent to use left/right arrows when autocomplete is open?
Or close it (and clear trigger stack) after caret move?

**Pull request merged**
