### PR TITLE
New autocomplete behavior

### PR DESCRIPTION
**Pull request by jukben**
#100 #101 

This is the prototype of the new behavior which should solve the issues above.

I'd appreciate feedback from @guidogast

Example
demoproject

### CODE REVIEW

**Comment by jukben** [comment]
(bot)

Hey! Thank you so much for your PR! I can see that everything is green 👏.

[Here is the playground for this revision](https://379-94480675-gh.circle-artifacts.com/0/example/index.html) 🚀

I hope everything is fine! ❤️

**Comment by jukben** [comment]
@guidogast Awesome. I've tuned a bit the CircleCI workflow, so now you can easily test the playground. The `(` and `.` trigger should be your use case. But it would be awesome if you can confirm that this behavior solves your issues. 👍

**Comment by guidogast** [comment]
Hi @jukben I've played around a bit in the playground you provided. It seems to do exactly what I'd expect 👍 . I couldn't check the configuration though, but it all feels good when using it. Good work!

**Comment by jukben** [comment]
Awesome @guidogast, I'll deploy it soon as 4.0.0, so you can try it intercorporate it into your project and see in the real environment. 👍

**Pull request merged**
