### PR TITLE
Never decrease index in listener

### PR DESCRIPTION
**Pull request by JelteF**
Doing the following will break otherwise, f2 will be deleted by the add of f3:
```js
let index = Listener.add(KEY_CODES.ENTER, f1)
Listener.add(KEY_CODES.ENTER, f2)
Listener.remove(index)
Listener.add(KEY_CODES.ENTER, f3)
```

### CODE REVIEW

**Comment by jukben** [comment]
That makes sense! Could you please guide me how have you discovered the issue? There has to be also check in `this.f` if the listener exists or it was removed, going to push it.

**Comment by jukben** [comment]
(bot)

Hey! Thank you so much for your PR! I can see that everything is green 👏.

[Here is the playground for this revision](https://762-94480675-gh.circle-artifacts.com/0/example/index.html) 🚀

I hope everything is fine! ❤️

**Comment by JelteF** [comment]
You were right about that my fixed missed the iteration part. The way I found it was that the events just stopped working after a long session with some navigation steps in between. And I think this was the reason for that.

**Comment by jukben** [comment]
Nice, `Object.values` are even better 👍 Thanks I'm gonna deploy it with fix from #124

**Comment by jukben** [comment]
Deployed as 4.2.3! 🚀

**Pull request merged**
